name: compute_onnx_from_chunks
inputs:
  input_raster: RasterSequence
  chunk: RasterChunk
output:
  output_raster: RasterChunk
parameters:
  model_file:
  window_size: 512
  overlap: .0
  batch_size: 1
  num_workers: 0
  nodata: 100
  skip_nodata: True
entrypoint:
  file: compute_onnx.py
  callback_builder: CallbackBuilder
dependencies:
  parameters:
    - model_file
    - window_size
    - overlap
    - skip_nodata
description:
  short_description: Runs the onnx model across chunks of the input rasters. 