name: segment_driveway
inputs:
  input_raster: Raster
output:
  segmentation_raster: CategoricalRaster
parameters:
  downsampling: 1
  root_dir: /opt/terravibes/ops/resources/driveway_models
  model_path: driveway.onnx
  window_size: 128
  model_size: 512
  overlap: .25
  batch_size: 1
  num_workers: 0
entrypoint:
  file: segment_driveway.py
  callback_builder: CallbackBuilder
dependencies:
  parameters:
    - model_path
    - downsampling
    - window_size
    - overlap
description:
  short_description: Segments the front of houses in the input raster using a machine learning model.