name: compute_shadow_prob
inputs:
  sentinel_raster: Sentinel2Raster
output:
  shadow_probability: Sentinel2CloudProbability
parameters:
  downsampling: 1
  root_dir: /opt/terravibes/ops/resources/shadow_models
  model_path: shadow.onnx
  window_size: 512
  overlap: .25
  batch_size: 1
  num_workers: 0
  in_memory: false
entrypoint:
  file: compute_shadow_prob.py
  callback_builder: CallbackBuilder
dependencies:
  parameters:
    - model_path
    - downsampling
    - window_size
    - overlap
description:
  short_description: Computes shadow probabilities using a convolutional segmentation model for L2A.