name: compute_cloud_prob
inputs:
  sentinel_raster: Sentinel2Raster
output:
  cloud_probability: Sentinel2CloudProbability
parameters:
  downsampling: 1
  root_dir: /opt/terravibes/ops/resources/cloud_models
  model_path: cloud_model2_cpu.onnx
  window_size: 512
  overlap: .25
  batch_size: 1
  num_workers: 0
  in_memory: false
entrypoint:
  file: compute_cloud_prob.py
  callback_builder: CallbackBuilder
dependencies:
  parameters:
    - model_path
    - downsampling
    - window_size
    - overlap
description:
  short_description: Computes cloud probabilities using a convolutional segmentation model for L2A.